name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository (main)
        uses: actions/checkout@v4
        with:
          # do a shallow clone of the repository from main branch only
          fetch-depth: 1
          ref: main

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js application
        run: pnpm run build

      - name: Upload .next artifact
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: .next  # Upload .next folder to be used by the deploy job
          
  deploy:
    name: Deploy to build branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository (build branch)
        uses: actions/checkout@v4
        with:
          # do a shallow clone of the repository from the build branch only
          fetch-depth: 1
          ref: build
      
      - name: Download .next artifact
        uses: actions/download-artifact@v3
        with:
          name: next-build
          path: next-build  # Download artifact to a folder named next-build

      - name: Replace old .next with new build
        run: |
          rm -rf .next
          mv next-build/.next ./.next
          rm -rf next-build

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .next
          git commit -m "Update .next folder from main build" || echo "No changes to commit"

          # Push changes to build branch
          git push origin build