name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository (main)
        uses: actions/checkout@v4
        with:
          # do a shallow clone of the repository from main branch only
          fetch-depth: 1
          ref: main
          
      - name: Set up Node with Corepack
        uses: actions/setup-node@v3
        with:
          node-version: 22
          check-latest: true
      - name: Enable and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.1 --activate

      - name: Install dependencies
        run: pnpm install
        
      - name: Setup .env
        run: |
          rm -rf .env
          touch .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env
          echo "NUDGE_API_KEY=${{ secrets.NUDGE_API_KEY }}" >> .env
          echo "NUDGE_OTP_ID=${{ secrets.NUDGE_OTP_ID }}" >> .env
          echo "NUDGE_SUBMIT_ID=${{ secrets.NUDGE_SUBMIT_ID }}" >> .env
          echo "NUDGE_NOTIFY_ID=${{ secrets.NUDGE_NOTIFY_ID }}" >> .env
          echo "HIRING_SUPER_EMAIL=${{ secrets.HIRING_SUPER_EMAIL }}" >> .env
          echo "HIRING_SUPER_NAME=${{ secrets.HIRING_SUPER_NAME }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> .env
          echo "NEXT_PUBLIC_ENV=production" >> .env

      - name: Build Next.js application
        run: pnpm build
        
      - name: Debug List files
        run: ls -R

      - name: Upload .next artifact
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: .next  # Upload .next folder to be used by the deploy job
          
  deploy:
    name: Deploy to build branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository (build branch)
        uses: actions/checkout@v4
        with:
          # do a shallow clone of the repository from the build branch only
          fetch-depth: 1
          ref: build
      
      - name: Download .next artifact
        uses: actions/download-artifact@v3
        with:
          name: next-build
          path: next-build  # Download artifact to a folder named next-build

      - name: Replace old .next with new build
        run: |
          rm -rf .next
          mv next-build/.next ./.next
          rm -rf next-build

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .next
          git commit -m "Update .next folder from main build" || echo "No changes to commit"

          # Push changes to build branch
          git push origin build